ALTER TABLE click_events ADD COLUMN IF NOT EXISTS country VARCHAR(2);
ALTER TABLE click_events ADD COLUMN IF NOT EXISTS city VARCHAR(255);
ALTER TABLE click_events ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE click_events ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE click_events ADD COLUMN IF NOT EXISTS isp VARCHAR(255);

CREATE INDEX IF NOT EXISTS idx_click_events_country ON click_events(country);